version: '2'

services:
  whoami:
    image: traefik/whoami:${WHOAMI_VERSION:-v1.6.1}
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.entrypoints=https"
      - "traefik.http.routers.whoami.tls=true"
      - "traefik.http.routers.whoami.rule=Host(`${WHOAMI_HOST}`)"

networks:
  reverse-proxy:
    external: true
